codecov:
  url: "https://codecov.io"        # [enterprise] your self-hosted Codecov endpoint
                       # ex. https://codecov.company.com
  slug: "Salesforce/nhal"   # [enterprise] the project's name when using the global upload tokens
  branch: master  
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...80"

  status:
    project:
      default:
        threshold: null

    if_ci_failed: error 
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no